---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
      #annotations:
      #prometheus.io/scrape: "true"
      #prometheus.io/port: "9113"
      #prometheus.io/scheme: http
    spec:
      serviceAccountName: nginx-ingress
      containers:
        - name: nginx-plus-ingress
          image: aknot242.azurecr.io/nginx-plus-ingress-nap-waf-dos
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: readiness-port
              containerPort: 8081
            - name: prometheus
              containerPort: 9113
          readinessProbe:
            httpGet:
              path: /nginx-ready
              port: readiness-port
            periodSeconds: 1
          securityContext:
            allowPrivilegeEscalation: true
            runAsUser: 101 #nginx
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsecops-poc
  annotations:
    appprotect.f5.com/app-protect-enable: "True"
    appprotect.f5.com/app-protect-policy: "devsecops"
    appprotect.f5.com/app-protect-security-log-enable: "True"
    appprotect.f5.com/app-protect-security-log: "logconf-elk"
    appprotect.f5.com/app-protect-security-log-destination: "syslog:server=172.19.0.4:5144"
    appprotectdos.f5.com/app-protect-dos-resource: "dos-protected"
    nginx.org/hsts: "True"
    nginx.org/location-snippets: |
      limit_except GET HEAD POST {
          deny all;
      }

spec:
  ingressClassName: nginx
  rules:
    - host: devsecops.hazy.beer
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dotnetcorewebapp
                port:
                  number: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    app: nginx-ingress
