---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devsecops-stage
nameSuffix: -stage
commonLabels:
  variant: stage
bases:
  - ../../base
patchesStrategicMerge:
  - ingress.yml
