---
apiVersion: appprotectdos.f5.com/v1beta1
kind: DosProtectedResource
metadata:
  name: dos-protected
spec:
  name: "devsecops-stage.hazy.beer"
  apDosPolicy: "devsecops-prod/dospolicy-stage"
  # apDosMonitor:
  #   uri: "webapp.example.com"
  #   protocol: "http1"
  #   timeout: 5