---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: devsecops
spec:
  ingressClassName: nginx-stage
  server-snippets: |
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff" always;
    add_header Content-Security-Policy "default-src 'self' https://devsecops-stage.hazy.beer https://devsecops-stage.hazy.beer; script-src 'self' 'unsafe-inline'; style-src 'self'; img-src 'self' data:; connect-src 'self'; font-src 'self'; object-src 'none'; media-src 'self'; form-action 'self'; frame-ancestors 'self';" always;
  host: devsecops-stage.hazy.beer
  routes:
    - path: /
      dos: devsecops-stage/dos-protected
      location-snippets: |
        limit_except GET HEAD POST {
            deny all;
        }
      action:
        pass: dotnetcorewebapp-upstream