name: DevSecOps GitHub Action CI-CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch- test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    ignore-tags:
      - "*"
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: edgar-rg
  AZURE_WEBAPP_NAME: edgar-devsecopspocappcontainer
  AZURE_NAP_NAME: edgar-nap-devsecopspocappcontainer
  ACR_NAME: aknot242
  SITE_NAME_STAGING: edgar-devsecopspoc-staging
  SITE_NAME_PROD: edgar-devsecopspoc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v2

    - name: DotNet Build
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - run: dotnet build -c Release DotNetCoreWebApp/DotNetCoreWebApp.csproj -o {env.DOTNET_ROOT}/app/build   

    - name: DotNet Publish
      run: |
        pwd
        dotnet publish -c Release DotNetCoreWebApp/DotNetCoreWebApp.csproj -o {env.DOTNET_ROOT}/app/build
    
    # Performs an Anchore container image vulnerability and compliance scan, 
    # and integrates the results with GitHub Advanced Security code scanning feature.
    # For more information on the Anchore scan action usage and parameters, see
    # https://github.com/anchore/scan-action.  For more information on
    # Anchore container image scanning in general, see
    # https://docs.anchore.com.
    # - name: Build the Docker image locally for Anchore Container Scan
    #   run:  |
    #     cd DotNetCoreWebApp
    #     docker build --file Dockerfile --tag devsecops/pocimage:latest .
    #     docker images
    
    # - name: Run the local Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
    #   uses: anchore/scan-action@v2
    #   with:
    #     image: "devsecops/pocimage:latest"
    #     fail-build: true
    #     severity-cutoff: medium
    
    # - name: Upload Artifact
    #   if: ${{ always() }}
    #   uses: actions/upload-artifact@v2.2.0
    #   with:
    #     name: anchore-vulnerabilities
    #     path: vulnerabilities.json

    - name: Az Login
      uses: azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: ACR Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_SERVERNAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push App Protect container
      run: |
        cd app-protect
        docker build -t ${{ secrets.REGISTRY_SERVERNAME }}/nap-dotnetcorewebapp:${{ github.sha }} -f NAP-App-Dockerfile .
        docker push ${{ secrets.REGISTRY_SERVERNAME }}/nap-dotnetcorewebapp:${{ github.sha }}

    - name: Build and push app container
      run: |
        cd DotNetCoreWebApp
        docker build -t ${{ secrets.REGISTRY_SERVERNAME }}/dotnetcorewebapp:${{ github.sha }} .
        docker push ${{ secrets.REGISTRY_SERVERNAME }}/dotnetcorewebapp:${{ github.sha }}

    - name: GitHub Container Scan
      uses: Azure/container-scan@v0.1
      with:
        image-name: ${{ secrets.REGISTRY_SERVERNAME }}/dotnetcorewebapp:${{ github.sha }}

    - name: Run ARM template deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: ./azuredeploy.json
        parameters: imageRegistryLoginServer=${{ secrets.REGISTRY_SERVERNAME }} imageRegistryUsername=${{ secrets.REGISTRY_USERNAME }} imageRegistryPassword=${{ secrets.REGISTRY_PASSWORD }} container1Image=${{ secrets.REGISTRY_SERVERNAME }}/dotnetcorewebapp:${{ github.sha }} container2Image=${{ secrets.REGISTRY_SERVERNAME }}/nap-dotnetcorewebapp:${{ github.sha }} siteName=${{ env.SITE_NAME_STAGING }}

    - name: OWASP ZAP Scan
      uses: zaproxy/action-full-scan@v0.2.0
      with:
        target: "http://${{ env.SITE_NAME_STAGING }}.westus2.azurecontainer.io/"
        rules_file_name: '.github/zap/rules.tsv'
        fail_action: true

    - name: Azure logout
      run: |
        az logout

  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Az Login
      uses: azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: ACR Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_SERVERNAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Run ARM template deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: ./azuredeploy.json
        parameters: imageRegistryLoginServer=${{ secrets.REGISTRY_SERVERNAME }} imageRegistryUsername=${{ secrets.REGISTRY_USERNAME }} imageRegistryPassword=${{ secrets.REGISTRY_PASSWORD }} container1Image=${{ secrets.REGISTRY_SERVERNAME }}/dotnetcorewebapp:${{ github.sha }} container2Image=${{ secrets.REGISTRY_SERVERNAME }}/nap-dotnetcorewebapp:${{ github.sha }} siteName=${{ env.SITE_NAME_PROD }}

    - name: Azure logout
      run: |
        az logout
